swagger: '2.0'
info:
  title: FastScore Login API
  version: '1.5'
schemes:
  - https
paths:
  /1/login:
    post:
      tags:
        - Login
      operationId: login_post
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          description: user name
          type: string
          in: formData
          required: true
        - name: password
          description: password
          type: string
          in: formData
          required: true
      responses:
        200: { description: Login successful }

